### ISSUE TITLE
Error loading

### ISSUE THREAD

**Issue by diimdeep** [utopiabound/redditp#3]
Not sure what is the problem. Reddit, imgur, gfycat works, but redgifs not.
FF 106
macos 10.15

![Screenshot 2022-08-31 at 12 46 55](https://user-images.githubusercontent.com/485713/187650602-e37e82ad-5176-4a90-b052-97b99cc25629.png)

**Comment by utopiabound** [comment]
This has been fixed.  redgifs went to embed only and it's supported now.
